export const state = {
  therapists: [],
  doctors: [],
  patients: [],
  appointments: [],
  protocols: [],
  notifSettings: [
    {id:'wa_rec',label:'Recordatorio WhatsApp 24h antes',desc:'Envía mensaje automático al paciente 24h antes de su cita.',icon:'📱',on:true},
    {id:'email_th',label:'Email al terapeuta al asignar cita',desc:'Notifica al terapeuta cuando se le agenda una nueva cita.',icon:'✉️',on:true},
    {id:'wa_noas',label:'Mensaje automático de inasistencia',desc:'Si el paciente no asistió, le envía mensaje para reprogramar.',icon:'📱',on:false},
    {id:'resumen',label:'Resumen diario al administrador',desc:'Al finalizar el día, envía resumen con asistencias e inasistencias.',icon:'📊',on:true},
    {id:'email_doc',label:'Notificar al doctor referente en alta',desc:'Al dar de alta a un paciente, notifica al médico que lo refirió.',icon:'✉️',on:false},
  ],
  currentDate: new Date(),
  currentWeek: 0,
  currentTab: 'agenda',
  dragData: null,
  facturaCounter: 10,
  thCounter: 10,
  docCounter: 10,
  patCounter: 10,
  apptCounter: 20,
  protCounter: 10,
  protCurrentPage: 0,
  editingTherapistId: null,
  editingDocId: null,
  editingPatientId: null,
  editingProtocolId: null,
  selectedColor: 'ca',
  selectedDocColor: '#E24B4A',
};
